services:
  - type: web
    name: wellness-agent
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python app/start_wellness_api.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: ENVIRONMENT
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY_BACKUP
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: wellness-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
